### ISSUE TITLE
Toolchain: Support Windows (again)

### ISSUE THREAD

**Issue by povrazor** [ludumdare/ludumdare#130]
Toolchain currently requires some exotic Linux knowledge to use. Fix that.

**Comment by gholdampf** [comment]
I managed to get DairyBox and Ludum Dare running on Windows 10, here's what I did:




# Command Prompt Signifiers:
CMD> windows command prompt
CYG$ cygwin command prompt
SSH$ putty connection to the virtualbox vm




# Step 0: Installing Dependencies
Follow the Pre Setup instructions here: https://github.com/ludumdare/dairybox#pre-setup-part-0
&nbsp;- Install GIT
&nbsp;- Install Virtual Box
&nbsp;- Install Vagrant
&nbsp;CMD> vagrant plugin install vagrant-exec
&nbsp;CMD> vagrant plugin install vagrant-cachier

**Windows Specific Additional Setup:**
&nbsp;- http://www.putty.org/ (you will only need to get 'putty.exe' from the downloads page)
&nbsp;&nbsp;&nbsp;Install Putty (this is to make an SSH connection to the virtual machine, you could use any SSH software you happen to have)
&nbsp;- https://www.cygwin.com/
&nbsp;&nbsp;&nbsp;Install cygwin (this is to run the makefile later)
&nbsp;&nbsp;&nbsp;&nbsp;- Don't do a full install, it will take a few minutes, but a full install took me about 7 hours
&nbsp;&nbsp;&nbsp;&nbsp;- Add "Devel" > "make: The GNU..." (click where it says "Skip" to add it to the pending install, it's a confusing interface)
&nbsp;&nbsp;&nbsp;&nbsp;- Also add the entire "PHP" category (click "Default" so it becomes "Install")
&nbsp;- https://nodejs.org/
&nbsp;&nbsp;&nbsp;Install the current recommended version of NodeJS


# Step 1: DairyBox and Ludum Dare
We needs special instructions here to keep our line endings correct for the Linux VM, if we installed git with the "core.autocrlf" config option set to "input", or if the repo gets a .gitattributes file (I imagine this will happen sooner or later) to enforce line endings, the instructions will be the same for Windows and *nix

**DairyBox:**
&nbsp;CMD> mkdir ludumdare
&nbsp;CMD> cd ludumdare
&nbsp;CMD> git init
&nbsp;CMD> git config core.autocrlf input
&nbsp;CMD> git remote add origin https://github.com/ludumdare/dairybox.git
&nbsp;CMD> git fetch

**Ludum Dare:**
&nbsp;CMD> cd www
&nbsp;CMD> git init
&nbsp;CMD> git config core.autocrlf input

&nbsp;IF JUST TESTING:
&nbsp;&nbsp;CMD> git remote add origin https://github.com/ludumdare/ludumdare.git
&nbsp;ELSE IF PLAN TO UPDATE, FORK AND THEN:
&nbsp;&nbsp;CMD> git remote add origin https://github.com/YOUR-USER-NAME-ON-GIT/ludumdare.git
&nbsp;&nbsp;CMD> git remote add upstream https://github.com/ludumdare/ludumdare.git

&nbsp;CMD> git fetch
&nbsp;CMD> git checkout -t origin/master


# Step 2: Building the Website
Working Directory: ludumdare/www/
CMD> npm install
CMD> npm install -g svgo less clean-css buble rollup uglify-js

Now start a Cygwin Terminal and navigate to the ludumdare/www/ directory, it will be somewhere in /cygdrive/, you can drag a drop the folder into the terminal to automatically type it's path in.

CYG$ cd <PATH TO ludumdare/www/>
CYG$ make
&nbsp;If there are errors you may need to install more cygwin packages, launch the installer again and install anything that the error referances, then (ONLY IF YOU HAD ERRORS, OR WANT TO REBUILD FROM A CLEAN STATE):
&nbsp;&nbsp;CYG$ make clean
&nbsp;&nbsp;CYG$ make


# Step 3: Updating the Server
We're finally going to boot the VM, and then we have to fix some things

Working Directory: ludumdare/
CMD> vagrant up
&nbsp;This will take a while the first time, it has to download the VM and set it up once this is complete you should be able to see the website at: http://ludumdare.org/ but we want to fix a few things on the server before we go any further

We have to connect to the virtual machine, we'll use Putty, because that's what I'm familiar with. Open "putty.exe" and type Host Name: "vagrant@127.0.0.1" Port: "2222", you can name and save it to make future connections easier, click connect, and when prompted for a password type "vagrant"

&nbsp;**First we will replace MySQL with MariaDB:**(https://github.com/ludumdare/ludumdare/issues/301)
&nbsp;&nbsp;SSH$ sudo apt-get remove -y mysql-server
&nbsp;&nbsp;&nbsp;Follow the Instructions here to install MariaDB: https://downloads.mariadb.org/mariadb/repositories/#mirror=accretive&distro=Ubuntu&distro_release=trusty--ubuntu_trusty&version=10.1
&nbsp;&nbsp;&nbsp;&nbsp;- It will ask to set a password (twice), just press ENTER without typing anything in.
&nbsp;&nbsp;SSH$ mysql --version
&nbsp;&nbsp;&nbsp;- The version should show that it's now using "10.1.19-MariaDB" or whichever version you installed

&nbsp;**Next we will update php:**
&nbsp;&nbsp;SSH$ sudo add-apt-repository ppa:ondrej/php
&nbsp;&nbsp;SSH$ sudo apt-get update
&nbsp;&nbsp;SSH$ sudo apt-get install -y php7.0 php7.0-mbstring php7.0-mysql
&nbsp;&nbsp;SSH$ sudo a2dismod php5
&nbsp;&nbsp;SSH$ sudo a2enmod php7.0

&nbsp;**Then we will initialize the server database:**
&nbsp;&nbsp;SSH$ cd ~/vvv/src/shrub/tools
&nbsp;&nbsp;SSH$ sudo ./table_create

&nbsp;**Finally we will restart the webserver:**
&nbsp;&nbsp;SSH$ sudo service apache2 restart


# Step 4: Injecting Some Content
To see the site in action we will make a user, and a post.

The VM startup script installs phpmyadmin for us.

Go to the site and try to sign up:
&nbsp;http://ludumdare.org/#user-register
&nbsp;&nbsp;- You wont get a real email, but you can find your authorization key in the MySQL database, go to phpmyadmin:
&nbsp;&nbsp;&nbsp;&nbsp;http://192.168.48.48/phpmyadmin/
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Sign in with Username: "root" Password: "root"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Navigate to "scotchbox" > "sh_user" and look for the "auth_key" related to the email you used, then go to this url:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;http://ludumdare.org/?id=1&key=<AUTH_KEY HERE>#user-activate

Now we can add a test post in phpmyadmin, anywhere in "scotchbox", use "SQL" to execute this query:
&nbsp;INSERT INTO `sh_node` (`id`, `parent`, `author`, `type`, `subtype`, `subsubtype`, `published`, `created`, `modified`, `version`, `slug`, `name`, `body`) VALUES (NULL, '1', '10', 'post', '', '', NOW(), NOW(), NOW(), '0', 'test-post', 'Test Post', 'This is a test post!')

Now if we go to http://ludumdare.org/ we should see that our test use has made a post!




I hope that helps!

I'll leave figuring out how to edit the site, rebuild it, pushing changes to your fork, and submitting a pull request as an assignment for the reader.

**Comment by zwrawr** [comment]
Tested this out and it works. 

The sql seems off though, it makes the title of the post the same as the name of the user that posted it.

**Comment by povrazor** [comment]
Yeah, that's because node 9 doesn't exist initially (only nodes up to 8 exist in a fresh install), and you've essentially assigned node 9 (i.e. the post you added) as the "thing" that posted it. :smile:

**Comment by zwrawr** [comment]
When we created a user that becomes node 9. 
Then the post is node 10.
The post's parent is root(1).
And the post author is us(9).

**Comment by gholdampf** [comment]
I originally had "VALUES (NULL, '1', '10', 'post', ..." in my comment but updated it when I realized I had created more than one user... you must have opened the page before I updated it. It's all understandable confusion.

I also have started looking into using mailcatcher again, it gave me trouble the first time I tried it. I figured since sendmail isn't installed on the VM by default php mail would fail and we could just get the auth_key from the database. ^_^ I agree that a GUI to show emails is a nicer solution though, and I think it's just changing an apache or php config setting to use mailcatcher instead of sendmail.

**Comment by povrazor** [comment]
It should be a simple matter of

```
vagrant ssh
./start_mailcatcher.sh
```
and visiting http://192.168.48.48:1080/

Then any time you expect an e-mail to send, it appears there.

**Comment by gholdampf** [comment]
I got mailcatcher to work, but I had to edit php.ini, if I just ran ./start_mailcatcher.sh in the VM, php would throw "sh: 1: /usr/sbin/sendmail: not found" and mailcatcher didn't see it.

I opened a pull request https://github.com/ludumdare/dairybox/pull/15 with my fix.

**Comment by povrazor** [comment]
Weird. I've never had to change anything, it just worked. After LD I'll test this stuff myself. :smile:

**Comment by povrazor** [comment]
Ah yes. Problem was that the mailcatcher config for the old PHP 5 setup wasn't copied to the PHP 7 setup. Now fixed.

**Comment by povrazor** [comment]
I want to test this myself, and once I do, and update the dairybox README.md, we can (finally) close this.

**Comment by zwrawr** [comment]
The clean-css node module has split in two. Theres now a sperate module for cli usage
* clean-css https://github.com/jakubpawlowicz/clean-css
* clean-css-cli https://github.com/jakubpawlowicz/clean-css-cli

Eslint you also now need eslint installed

So, instead of
```npm install -g svgo less clean-css buble rollup uglify-js```
you should do 
```npm install -g svgo less clean-css clean-css-cli buble rollup uglify-js eslint```

**Comment by zwrawr** [comment]
And a most of the config is now handeled for you (getting php7 and MariaDB ect.)

**Comment by zwrawr** [comment]
Symlinks are not working for me on windows (running ```vagrant up``` as admin).

Also npm doesn't support symlinks with vigrant/docker on top of windows, so the ```npm install``` line in bootstrap.sh needs to be changed to ```npm install --no-bin-links```

**Comment by povrazor** [comment]
> The clean-css node module has split in two. Theres now a sperate module for cli usage
Cool. I noticed this while helping someone get things working on Mac. These changes are in.

> And a most of the config is now handled for you (getting php7 and MariaDB ect.)
Yes.

> Symlinks are not working for me on windows
The `/static/` symlink shouldn't be needed. It's more a convenience. 

I'm currently testing a tweak to the install script that should use `--no-bin-links` if a Cygwin host is detected.

**Comment by povrazor** [comment]
Okay, I've tested the environment on Windows and it is working.

As it turns out, Cygwin isn't even required. The latest version of **GIT** actually includes an optional Unix environment. That can be used for checking out the code, starting the VM, among other things. After that, you should `vagrant ssh` and do everything from inside the VM (as that's a true Linux environment).

**Comment by povrazor** [comment]
Okay, the Node/NPM related symlink issues are fixed now. However there is still this:

```
==> default: Done (Apache Ports).
==> default: ln:
==> default: failed to create symbolic link ‘/vagrant/www/public-ludumdare.com/-/all.js’
==> default: : Protocol error
==> default: ln:
==> default: failed to create symbolic link ‘/vagrant/www/public-ludumdare.com/-/all.css’
==> default: : Protocol error
==> default: ln:
==> default: failed to create symbolic link ‘/vagrant/www/public-ludumdare.com/-/all.svg’
==> default: : Protocol error
==> default: ln:
==> default: failed to create symbolic link ‘/vagrant/www/public-jammer.vg/-/all.js’
==> default: : Protocol error
==> default: ln:
==> default: failed to create symbolic link ‘/vagrant/www/public-jammer.vg/-/all.css’
==> default: : Protocol error
==> default: ln:
==> default: failed to create symbolic link ‘/vagrant/www/public-jammer.vg/-/all.svg’
==> default: : Protocol error
==> default: ln:
==> default: failed to create symbolic link ‘/vagrant/www/public-jammer.bio/-/all.js’
==> default: : Protocol error
==> default: ln:
==> default: failed to create symbolic link ‘/vagrant/www/public-jammer.bio/-/all.css’
==> default: : Protocol error
==> default: ln:
==> default: failed to create symbolic link ‘/vagrant/www/public-jammer.bio/-/all.svg’
==> default: : Protocol error
```
A bit of a design mistake on my end. Okay then.

**Comment by povrazor** [comment]
Alright, this should be fixed now. `--no-bin-links` was problematic, so it's no longer used. Instead I'm using Windows actual symlink support now.

**IMPORTANT**: You need to run your bash/cmd shell as an **Administrator**! Symlinks will not work without it. If you forget to run as an administrator, the site may still work, but you wont be able to use debug mode (i.e. http://ludumdare.org?debug).

**Comment by zwrawr** [comment]
This works for me now !
