### ISSUE TITLE
'(Un)Follow Thread' button doesn't respond

### ISSUE THREAD

**Issue by bremco** [ludumdare/ludumdare#1533]
If I click 'Unfollow Thread' (or 'Follow Thread'), the button doesn't change to it's respective antonym. I can't really tell if clicking the button does anything anymore.

**Comment by local-minimum** [comment]
I can verify that this is a bug, and that it is due to one missed name-change in the back-end. Hopefully Mike can merge my PR when he wakes up... Though people tend to be busy this time of year.

In the meantime I would suggest going to your notifications feed and make sure you haven't unchecked `Comment` notifications. That should hide the notifications you probably wanted to avoid by unfollowing the thread.
