### ISSUE TITLE
click on one notification clears all of them

### ISSUE THREAD

**Issue by bremco** [ludumdare/ludumdare#1556]
When I have multiple notifications, and select one of them from the drop-down menu, all of them are cleared (I've noticed this multiple times):

![2jan_ldjam_notify0](https://user-images.githubusercontent.com/30440932/34517822-00d6aed2-f07d-11e7-91b7-2bb3a6089d7b.png)

![2jan_ldjam_notify1](https://user-images.githubusercontent.com/30440932/34517836-09bfa6ca-f07d-11e7-921b-ceea317cc6f4.png)

Then, after I've clicked the notification, I experience loading issues until I do a hard refresh with F5 (for example, _only_ the comments loading on the post the notification was for, then an 'empty feed' after you click on the main-site logo...;

![2jan_ldjam_emptyfeed0](https://user-images.githubusercontent.com/30440932/34517857-129b99e8-f07d-11e7-921f-43ce6c62bf1b.png)

![2jan_ldjam_emptyfeed1](https://user-images.githubusercontent.com/30440932/34517884-25a95462-f07d-11e7-9807-11985c5023cf.png)

... and/or the notification-page (not the drop-down, but the actual page) stuck in 'perpetual load':

![2jan_ldjam_notify_r0](https://user-images.githubusercontent.com/30440932/34517900-30c89088-f07d-11e7-99ad-46d13e8d8b4f.png)

![2jan_ldjam_notify_r1](https://user-images.githubusercontent.com/30440932/34517904-3437a9ac-f07d-11e7-978e-f215d934e482.png)

I think these are related, because I can't seem to reproduce them when I've got no notifications. (Explaining my difficulties earlier.)

**Comment by local-minimum** [comment]
So I think this may be two things.

* Read notifications goes by highest read notification ID, and therefore it isn't possible to cherry-pick which you have seen or not.
* ...  but there's also a design thing that should be discussed, I think it marks all that you are seeing as read, and perhaps it should only mark up until the one you clicked. That could be an issue.
* Finally the error, I've been meaning to report it too. I have a feeling it has to do with some of the nav-changes caused by some of the notifications (as well as the thing causing an error there for you).

**Comment by local-minimum** [comment]
I think the issue should be resolved now. Let me know if anything lingers.

**Comment by bremco** [comment]
Thanks!

I waited a bit to see if I could test this with _more_ than one notification (wasn't able to in  the end), but since the other (sub-)issues are resolved --as far as I can see-- I guess I should close this one at least, since if it crops up again it's probably unrelated?
