### ISSUE TITLE
Publish post issues

### ISSUE THREAD

**Issue by local-minimum** [ludumdare/ludumdare#1562]
The dialogue about needed length of the title is sometimes telling lies:

![image](https://user-images.githubusercontent.com/8041100/34644787-9212857a-f33d-11e7-815c-ee794efa8df5.png)

Once you publish the thing you are also free to edit the title down to a single character and save it. Even down to a single `.` or even more strangely if you edit it down to a single ` ` (space).

**Comment by mikekasprzak** [comment]
The limit is 3 alpha-numeric characters.

**Comment by local-minimum** [comment]
Then we should have that in the dialogue. And also refuse edits that make it shorter.

**Comment by mikekasprzak** [comment]
Yes

On Jan 7, 2018 03:08, "Martin Zackrisson" <notifications@github.com> wrote:

Then we should have that in the dialogue. And also refuse edits that make
it shorter.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/ludumdare/ludumdare/issues/1562#issuecomment-355806699>,
or mute the thread

**Comment by zwrawr** [comment]
fyi: that error message is taken directly from the api. 

https://github.com/ludumdare/ludumdare/search?utf8=%E2%9C%93&q=Error%3A+Name+is+too+short&type=

We should probably make the error text user friendly, not just parrot the api error back to the user.
