### ISSUE TITLE
Cookie-less Login/API Keys

### ISSUE THREAD

**Issue by mikekasprzak** [ludumdare/ludumdare#1642]
Well since security software like Norton hates us (browsers love us, "Security" software hates us), we're going to have to subvert it.

This means gutting and replacing PHP sessions from the Auth API and replacing it with a key exchange, storing the key in `localstorage`, and including it with any requests for private information/a change. This also potentially means switching a bunch of calls to `HTTP POST` requests instead of `HTTP GET` for security reasons, so users don't accidentally share their session key.

The cookie-less method is also effectively the same thing as API keys, but API keys tend to be fixed numbers, and I want to scramble these regularly for security's sake.

This potentially fixes all of the logout issues, and makes the server's timeouts on the "session" the only factor in deciding how long a key lives, rather than having to juggle Cookie expiration too. 

The only remaining logout issue would be users that set their browser to clear cookies (as this tends to also make the browser discard `localstorage`). A check would have to be included to see if `localstorage` is available in the first place (some aggressive settings cause there to be no `localstorage` object).

**Comment by mikekasprzak** [comment]
This affects #1175

**Comment by amcgregor** [comment]
Apologies for "butting in" to the conversation here; I'm not a user, but highly interested web developer.  Here's some related reading after this issue was brought up on Freenode IRC's `##webdev`:

* [HTML5 localStorage security: Bad idea.](https://stackoverflow.com/a/3719435/211827)
* [OWASP on localStorage](https://www.owasp.org/index.php/HTML5_Security_Cheat_Sheet#Local_Storage)
* [NCC Group: JS Crypto Considered Harmful](https://www.nccgroup.trust/us/about-us/newsroom-and-events/blog/2011/august/javascript-cryptography-considered-harmful/) (to counter the "let's just encrypt everything" alternative solutions from the SO post)

Additionally, it would be awesome to clarify "security software … hates us".  Why?  I'm very interested in what that's about.  Additionally, if cookies are evil (though they do automate the delivery of tokens on requests, and cookies required for the operation of a site and not used to track browsing behaviour require no notification under the GDPR), what is the proposed alternative?  POST form-data?  Authorization header?

Thanks, and keep on keeping on!  :)
