### ISSUE TITLE
Typing a "y" in the password field when logging in closes dialog and produces an error message

### ISSUE THREAD

**Issue by Nicate** [ludumdare/ludumdare#1699]
The following error message is shown:

Session Expired
Oops!!
It looks like your session expired (and yes, it's probably a bug).
Log in again to continue what you were doing.

I gots them Firefox 61.0.1 on them Windows 7. Dunno what else to tell ya. Didn't happen during previous Ludum Dares.

**Comment by Nicate** [comment]
Oh yeah, this also means I can't log in. If this happens for other people it's possible a lot of people can't log in.

**Comment by Samusoidal** [comment]
What page are you logging in from? If it's the Theme Slaughter page, try logging in from the homepage as it doesn't use keyboard shortcuts Y and N.

**Comment by Nicate** [comment]
Whew, at least that means I can join in two weeks :D

**Comment by local-minimum** [comment]
Same as #1700 then?

**Comment by Samusoidal** [comment]
Yup, duplicate.

**Comment by local-minimum** [comment]
I'm the guilty one, but with the organization of the site's code I think the most tangible way is to on that page continuously check if user is still checked in an disable Y/N key capture when user gets logged out.

Unfortunately Mike is MIA due to pollen and I have quite a few PR up so I'll at least wait until those have been merged.

**Comment by mikekasprzak** [comment]
#1592
