### ISSUE TITLE
receiving too many ratings for what was given out

### ISSUE THREAD

**Issue by bremco** [ludumdare/ludumdare#1726]
This might be some bizarre fluke, but I get a _lot_ more ratings in return to everything I give out than I used to in other iterations of LD (where it was more 1-for-1, which seems a lot more sustainable).

24 people rated my game, while I have only rated 8 myself! Hard to complain, and yet I have to :-)

I thought at first it might be to-do with the new mini-games-viewer on the main page, but that seems more and more unlikely as the effect becomes bigger.

![42_strange_ratings_screenie2](https://user-images.githubusercontent.com/30440932/44116104-dfaf36aa-a00f-11e8-986a-1988684cd27f.png)

In case you need it; a link to [my game-page](https://ldjam.com/events/ludum-dare/42/minicipality) as well.

E.T.A.: Hm ... it's a 1:3 rating, and I updated the page in quick succession after my initial creation (1) exactly 2 times. Maybe something changed so that this counts as 3 games for 'decide the number for the reciprocal ratings goal' purposes somehow?

**Comment by local-minimum** [comment]
There could be a few things. First don't forget that you have quite good karma there. It's not only the number of games you rate but quality of comments count too.

Then it could also be that people who know you from previous LD selectively play your game. I play the stuff off people I follow early on. You also scored quite high last LD so you might have more followers.

But it could also be a fluke. Since the site was so strained, Mike had to pause the scripts that update the balance for smart scores so jammers could submit their games. If you had a good balance when he hit pause, you would have gotten more ratings. I think.

**Comment by mikekasprzak** [comment]
Yeah if you submitted early enough, metrics updates were stopped for about an hour. But @local-minimum is right, you have really good feedback karma, so this might just be the result of that good feedback. The system is tuned in such a way that good feedback is more valuable than scores in the eyes of visibility. It doesn't have as quick of an effect as shotgunning a lot of reviews, but a single good review can score a lot of karma.

**Comment by ajayyy** [comment]
If you post your game on itch.io, many people organically find it there. It would be cool if @leaf could maybe implement the smart filter through the api on itch.io as well.
