### ISSUE TITLE
password confirmation validator

### ISSUE THREAD

**Issue by McFunkypants** [ludumdare/ludumdare#309]
The password confirmation validator displays an X even if passwords match, UNTIL you tab away from the field. Suggest checkmark while typing, not only after losing focus.
![screenshot-11-28-2016-10](https://cloud.githubusercontent.com/assets/2111957/20696794/86d1df34-b5aa-11e6-81ae-648ffb395385.png)

**Comment by povrazor** [comment]
Yep. Needs to be fixed.

**Comment by zwrawr** [comment]
Looks like this happens because onChange doesn't get called when the input is changed, it gets called when those changes get committed.
> This event is fired when the contents are committed and not while the value is changing.
[Mircosoft: change | onchange event](https://msdn.microsoft.com/en-us/library/ms536912(v=vs.85).aspx)

**Comment by povrazor** [comment]
Yes it's definitely onChange. But there's also the 'arrow key' bug, which I should be addressing soon, since I need working arrow keys. This'll will hopefully get fixed along the way. I just need to make sure it's *ONLY* the password checks that use the keyboard event (`name` would hammer the server every keypress).

**Comment by zwrawr** [comment]
Fixed by #470
