### ISSUE TITLE
You can <3 posts without being logged in

### ISSUE THREAD

**Issue by pta2002** [ludumdare/ludumdare#458]
It also let's you <3 again if you refresh the page

**Comment by Ulydev** [comment]
This is due to https://github.com/ludumdare/ludumdare/blob/master/src/com/content-post/post.js#L21
Removing the if check would possibly fix the issue.

If anonymous users are not allowed to <3, there should be a server-side check instead of the client doing it itself.

**Comment by Ulydev** [comment]
@povrazor , I can take care of this issue if you'd like. Are anonymous users allowed to love posts?

**Comment by zwrawr** [comment]
Anon users *should not* be allowed to love posts, that a really good way to get spam.

**Comment by Ulydev** [comment]
@zwrawr Alright, I'll try to dig into the API to add a logged-in check.

**Comment by zwrawr** [comment]
I was about to push a pr for this, but you seem to know js better than me so your fix will probably be cleaner.

The logged on check used else were in the code base is
```
        // if we have a user let them love stuff else get them to log on
        if( this.props.user && this.props.user.id ){
            // user is logged on so they can love stuff
    		if ( this.state.loved ) {
```

**Comment by Ulydev** [comment]
The problem is, this is done client-side and is very easy to bypass. Are we going for the super secure stuff and doing server-side checking, or is this alright for now?

**Comment by zwrawr** [comment]
There wasn't any server side checking before. So whilst it is an problem, i'd say its beyond the scope of this issue and warrants is own issue.
If love dosent have it then follow(star) dosent have it ect.

But fixing it is more important than in which issue it gets fixed :)

**Comment by WilliamDASILVA** [comment]
Don't know if it's related but the current like button is not being updated as the user refresh the page.
I mean, if I like a post then I refresh the page. The button doesn't tell me if I already liked that post. (the <3 isn't red).

**Comment by zwrawr** [comment]
The hearts stays red for me. . .

**Comment by WilliamDASILVA** [comment]
@zwrawr Ah yes.. I was logged-out and I didn't saw. My bad then. It happens only when we're anon.

**Comment by povrazor** [comment]
This is actually by design.

https://github.com/ludumdare/ludumdare/blob/master/public-api/vx/node.php#L213

The reason for this is to allow a level of interactivity for users that do not yet have accounts. Currently the event is targeted at developers, but this is one method for non-developers to be part of it.

For the sake of security though, anonymous love is limited to 1 love per node per IP address. It's also (at this time) the only thing you're allowed to do without an account.

It can technically be used to give your posts an extra Love, but as far as sorting and filtering is concerned, it just means we up the minimum.

For reference, Love has always worked this way, even on the old site. The minumum threshold before anything happened was 4 love. If "loving" does become a more common thing, this number will change.

**Comment by povrazor** [comment]
Now as for why when you refresh the love of a non logged out user doesn't stick, this is also by design.

Shared IP addresses are very common at Jam sites, so this is a workaround-fix for them primarily. Otherwise, the person beside them would directly affect the red :heart:'s they see.

Not seeing red :heart:'s is a cue that you're not logged in.

**Comment by Ulydev** [comment]
> Now as for why when you refresh the love of a non logged out user doesn't stick, this is also by design.

I think it was related to this code
```
if ( props.user ) {
			$NodeLove.GetMy(/*props.user.id,*/ props.node.id)
			.then(r => {
				//console.log( r ) ;
				this.setState({ 'loved': r });
			});
		}
```

When a user is logged out, the if block doesn't execute and makes the 'loved' state always false by default. That means you can refresh the page (and the state) and love again indefinitely.

**Comment by povrazor** [comment]
But on the server side, this fails, as not logged in users are not allowed to request the list of love. Again, this is by design to make sure there's a cue that you're not logged in.

Loving multiple times has no ill effects. There is only ever a maximum of 1 love entry per IP address.

**Comment by Ulydev** [comment]
I think I understand now. Thanks for clearing this up!
