### ISSUE TITLE
Improve the TV Widget

### ISSUE THREAD

**Issue by StormBurpee** [ludumdare/ludumdare#543]
Currently, it is forced to being two lines high, regardless of if the text only fills one line.

> **_PoV on Pull Request #542_** 
> Yeah, it's max 2 lines of description/title, since one was never enough, and some people tend to have no restraint.
>
> There might be a better way to design that. The key thing I wanted to avoid though is giving external users some way to control the height of that box.

**Low priority**

**Comment by povrazor** [comment]
![fitted](https://cloud.githubusercontent.com/assets/1570313/24651960/c99dd762-18fd-11e7-9fba-cab18e88dbe3.png)

I'm open to any improvements that can be made to sidebar TV widget. I'm not entirely happy with my design, but it's functional and covered the initial goals I had for it.

Things I do like:

* How the play button works (hover over the stream, the background goes to solid red). It's consistent with all the other hovers. The transparent black gives it a bit more shape, helps define it without outright hiding what's beneath. The Zoom is classy. :wink:
* The details around the active stream (LIVE, Service+Username, Viewers).
* That the widget never changes shape. There's no way for data pulled from 3rd party websites to manipulate the shape. Users viewing the website can change the shape by resizing the window, but not smartypants Twitch users.
* The flickering **LIVE** dot is cool, but if there's a good reason to get rid of it tell me.

Things that could be better:

* Being able to visually know from the 3 streams which one is actually selected
  * The key here is that it shouldn't draw your attention away from other things on the page. It's a detail you only care about when looking at the TV widget.
* The color scheme? Monochrome is probably right, but I'm not entirely sure I picked the best combination of the monochrome colors.
  * Shades are `@COL_N` family (`COL_NDDDDD` to `COL_NLLLLL`, where more D's is darker, and more L's is lighter, 5 of either is the brightest/darkest color). 
  * Palette is here: https://ludumdare.org/palette/
* The quotes? People can say anything they want in their Twitch title, and it can be of any length. It's something. *shrug*.
* I can't decide if **LIVE** looks best with a white background, or white on a red background with white dot.
* The size of the 'open in new window' hover icon is possibly too small.
  * It could probably use a transparent back background like the play button has
  * scaling from the corner (instead of the center) is odd

In general I want the widget to be roughly as big as it is now. There are other considerations that may come up later.

* Eventually `ludumdare.com/tv` will be the TV landing page. I have a dummy button beneath the widget in there right now that sends you to our brand new Community on Twitch. That will go away.
* There is more media content than Live streams. We also have (non live) YouTube videos. 
  * They don't necessarily need to go in the sidebar widget though
  * We have keynote videos. Those are not live, but we used to put a little banner in the sidebar to promote them. I don't know if this is something that would make sense to replace a live stream (and for how long).
* We may eventually introduce a radio feature too. It should be _somehow_ related to the widget.

The TV widget doesn't have to be everything. The `/tv` page can shoulder our greater media needs. That said, the entire point of the widget is to highlight video that is important in that moment. This could include things like keynote videos, talks from conferences or interviews about Ludum Dare, Lets Play videos of games, featured streams (like when when LD starts doing broadcasts), and so on. 

It's a summary of what video content is important in the moment.

**Comment by povrazor** [comment]
The TV Widget also regularly polls for updates, but skips it if you don't have the browser window in focus.

Currently the polling waits a few minutes before it checks for updates. This is because .. uh, I think Jammer TV isn't caching results. The real server checks for updates every minute. So just to avoid hitting the server too often. When it's out of focus, the update check time drops to 15 seconds or so. However, it also checks if it has focus, and will thusly do nothing if it doesn't, so this operation is cheap, it's just not event driven.

Alas this isn't exactly the best UX.

Ideally it should probably invalidate the stream data shown once the data it has gets a certain age, and request fresh data after re-gaining focus... within reason. You shouldn't be able to ALT+TAB your way to refresh the streams. It should be passive and cheap. Again the current data should have an expiration, and a regain focus event should be triggered that refreshes it.

I've also seen it stop working. I haven't watched it closely though, but I'm sure there's something in the log.
