### ISSUE TITLE
Small graphical issue with spinner

### ISSUE THREAD

**Issue by zwrawr** [ludumdare/ludumdare#581]
Just a small issue on the spinner graphic.

![](http://image.prntscr.com/image/3c509ca1b089492692ffcd512085a3b5.png)
![](http://image.prntscr.com/image/8a469eee21d64ef18ddaf236a1c02eb9.png)

**Comment by povrazor** [comment]
Yeah, this one has been haunting me. Only appears in Chrome. The element has a CSS rotation transform applied to it.

File is `/src/icons/icomoon/spinner.svg', but when I looked I didn't see an artifact in the file.

**Comment by povrazor** [comment]
If anyone is feeling like a super-detective, feel free to try and solve this.

`src/com/nav-spinner/` is where the code is, but in theory it should be reproducible without our codebase.

My best guess is it's either an artifact caused by CSS rotations in Chrome, or there's something in the actually vectors that is causing that.

Of course, if a standalone app that used the raw SVG file doesn't do it, then it's potentially something about my SVG pipeline.

**Comment by Aurel300** [comment]
Maybe it's relevant, testing on Chrome (57.0.2987.133 64-bit, up-to-date at this moment) on OS X 10.9.5, and could not reproduce the issue. The spinner looks fine, with no white line.

**Comment by povrazor** [comment]
OMG OMG! 

![googleyay](https://cloud.githubusercontent.com/assets/1570313/25064886/747b9aa2-21d2-11e7-965b-e7ba9ede206a.png)

Google Fixed it! I'm so happy!!

**Comment by povrazor** [comment]
:cry: I stand corrected. It's just more subtle now. :sob: 

![stillbroke](https://cloud.githubusercontent.com/assets/1570313/25071365/d3c89860-2282-11e7-8778-2599ef997331.png)

**Comment by Noojuno** [comment]
Strangely in my attempts to fix this I became unable to reproduce this on both my local version and the live version.

**Comment by povrazor** [comment]
I'm thinking it's a Chrome bug (after all, Firefox has no issues).

What should probably be tried is swapping out the graphic for one of the other SVG shapes, just to see if it still happens.

**Comment by zwrawr** [comment]
It has the border even if the svg image isn't there. 
I broke the svg pipeline on my VM for a while and ended with just the line spinning.

**Comment by zwrawr** [comment]
Its also resolution dependent so if you zoom in you might start seeing it @Noojuno .
![ldspinner_1png](https://cloud.githubusercontent.com/assets/18352787/25126426/33e7957c-242a-11e7-994e-7a3ca765003a.PNG)
![ldspinner_2png](https://cloud.githubusercontent.com/assets/18352787/25126424/33e6908c-242a-11e7-84df-24b210d2b9a5.PNG)
![ldspinner_3png](https://cloud.githubusercontent.com/assets/18352787/25126425/33e6b40e-242a-11e7-91cf-5403b56935cb.PNG)
![ldspinner_4png](https://cloud.githubusercontent.com/assets/18352787/25126427/33e82a50-242a-11e7-97b2-b2391e60080e.PNG)

**Comment by Noojuno** [comment]
@zwrawr Can you get it to reproduce if you remove the drop-shadow filter? I can't but with how picky this bug is I'm not entirely sure if it's just not displaying.

**Comment by povrazor** [comment]
Who knew that "hey, I should use this and make it spin while things load" would be the source of so much pain and frustration. ;)

**Comment by Jezzamonn** [comment]
Do you want me to submit a change to the Google codebase? ;)

**Comment by Aurel300** [comment]
Does it happen if you isolate the spinner symbol from the SVG symbol table? It might have something to do with Chrome creating a texture atlas with all the symbols, then showing the borders of adjacent symbols.

Or possibly changing the view box of the resulting SVG to be sliiiightly bigger than the SVG itself, because as you said, the vector goes all the way to the edges.

**Comment by zwrawr** [comment]
@Noojuno Thats the issue. the drop shadow

With shadow and glitch
![](http://image.prntscr.com/image/6a0d0ea38ac9449d9e7af45ff90627b8.png)

Without shadow and glitch
![](http://image.prntscr.com/image/7862057ed80042bcaee0b37f929d4986.png)

**Comment by povrazor** [comment]
Nice. Good detective work people. :smile:

**Comment by Aurel300** [comment]
So we will have ugly shadowless spinners? :)

**Comment by povrazor** [comment]
The spinner, since it's kind of its own thing, we could customize the SVG for it to include a shadow. As far as I know it's the only SVG that is ever rotated.

There's also the question if SVG drop shadows are affected by the same bug (that is a thing right, or is it just fuzzed SVG geometry?).

Or just duplicate the shape, scale it slightly (by adding outlines, then collapsing the outlines), hardcode the color to black with very low alpha (0.2 or something).

**Comment by zwrawr** [comment]
You can add a drop shadow to the svg but it does not extend beyond the svg.

![](http://image.prntscr.com/image/ea566a0b573949948bc479a4cb4048a9.png)
(color changed so its easyer to see)
