### ISSUE TITLE
[Theme voting] Order of choices

### ISSUE THREAD

**Issue by zwrawr** [ludumdare/ludumdare#632]
Currently the order of choices is +1,  0, -1.
![](http://image.prntscr.com/image/5d7589d30bf045b9b4971d99065dfcb9.png)

> (@timbeaudet)
I feel +1 0 -1 is backwards, the number-line typically works like: -1 0 1 

As tim says this is backwards to how these numbers are normally displayed.

**Comment by egordorichev** [comment]
And maybe we better change the labels to something more understanable. For example, 👍 , 👎 👌 or something...

**Comment by zwrawr** [comment]
I think +1 and bright green and -1 and red would be pretty hard to get confused about.

**Comment by egordorichev** [comment]
Yes, but they are gray.

**Comment by Jezzamonn** [comment]
Also remember colour-blindness. Red and Green in particular are two colours
you shouldn't rely on as the only source of information. Fortunately the
+1/-1 work.

I personally think the number system we use makes sense

**Comment by povrazor** [comment]
Looks like this is how we used to do it.

![oldcomment](https://cloud.githubusercontent.com/assets/1570313/25098646/59c143aa-2377-11e7-9015-a958c6df86a9.jpg)

I'm open to changing it if there's a good reason.

**Comment by timbeaudet** [comment]
I guess it has always been _backwards_ but look at what I've started. The only reason I'm, for the change is following a more natural number-line.

**Comment by povrazor** [comment]
If somebody wants to make the tweak to the code `src/com/content-event/event-list.js` (??), I will accept it.

**Comment by povrazor** [comment]
Happy Birthday Tim, courtesy of @zwrawr. :smile:

![zakfix](https://cloud.githubusercontent.com/assets/1570313/25101591/dc1363d2-2382-11e7-8ec6-cb64815841ce.png)

**Comment by povrazor** [comment]
About as many people that complained about the order being backwards complained that the original order was better. Main criticism is that "positive first" is more positive.

**Comment by povrazor** [comment]
Jordan Carroll reached out to me on twitter and had a great point. I asked him to post here, but I couldn't wait. :wink:

> Hey! Suggestion for Theme Voting: what if we had three ranked choices instead of +1/-1 on each?
> 
> I.e. Three choices to get +30, +20, and +10 or somesuch. Would be more positive than the final choices all having a large negative total. :)

***

I've always disliked having to report negative scores for themes. If we ditch the `-1` and add a `+2` that should change the tone nicely. Even though it's effectively the same, positivity FTW. :+1: 

Then comes the question of

```
+0 +1 +2
```
vs.

```
+2 +1 +0
```

:wink:

Also the colors.

**Comment by timbeaudet** [comment]
Oy vey, look what I started... I'm sorry y'all.

**Comment by povrazor** [comment]
Hey this whole website redesign from-the-ground-up is about making things better. We _should_ be questioning every decision. :wink:

**Comment by endlessplumber** [comment]
Although it's the same mechanically, +0 +1 +2 seems a bit arbitrary to me. 
+0 Implies "I'm neutral towards this theme"
+1 Implies "I like this theme some?"
+2 Implies "I like this theme...2x better than +1?"
With -1/0/+1 you at least get a dislike/like/neutral scale.

You could take the YouTube approach and track likes and dislikes.
You could take the Twitter approach and only track likes.
You could take the Reddit approach and track the delta between likes and dislikes.

I think it's worth noting that none of these platforms have a 'click for no change' option. It might simplify things if you had a positive vote, a negative vote, or do nothing to express neutrality/apathy. 

Alternatively, if all the negativity was handled in the Theme Slaughter, just have a like button for the remaining themes.

**Comment by cdrch** [comment]
There was a bit of conversation on IRC about positive to the left making a positive vote the "primary" choice. This was some context provided (afraid I lost who provided the link): https://ux.stackexchange.com/questions/58344/upvote-downvote-button-order

I'll be the first to admit I don't fully understand the implications - votes have been heavily negative in the past, particularly in the last few LDs, so does that mean the primary choice will be selected the least? Or that could simply be a thing which tends to happen when people get emotionally involved with the idea of their favorites winning and a large group of the total participants will always default to mostly negative votes.

Of course, the majority of websites that I have seen which have a horizontal layout of positive and negative things put the positive on the left. I suspect that either there is a fair bit of research that drove so many websites to that decision, or it seems natural (for possibly hard to understand reasons), or it just has become a sort of default. Any of those reasons are worth considering.

I'm not a fan of _not_ having a negative vote, as a theme you hate could make it past the Slaughter and I rather like being able to downvote a theme that is, say, highly similar to a past theme (though having a negative option at all may inevitably lead to the large negative scores we normally see, which I dislike even more). I do like having a neutral choice, as it feels more active - explicitly choosing to have a neutral opinion on a theme. I think moving to a +2 / +1 / +0 scale would just shift things - 0 would not longer be the neutral choice, +1 would be - but might indeed make things feel more positive.

There is also the _very_ different alternative of ranking all themes relative to each other; Theme A is 1, Theme B is 2, etc., then granting the top theme 20 points (or whatever works for the number of themes), the next-to-top 19 points, repeat down to the final point. I only mention this as a side note, since I brought it up during a conversation on this the other day; after thinking on it, I prefer something closer to what Ludum Dare has now.

**Comment by Jezzamonn** [comment]
I agree, having negative votes is important I think and although +0 +1 +2 is technically the same it feels very different.

I also want to say that -1/0/+1 is the way that makes the most sense to me :)  But it's very much a 'bike shed' style issue. It's very trivial, and so everyone has an opinion. Will it really change anything? Almost definitely not. So we should just make some decision and move on, I think.

On ranking the categories: I think ranking themes takes more effort, and you lose the ability to only vote up a few (or only vote down a few).

**Comment by Ploogle** [comment]
On the note of repeat themes, I wonder if during the slaughter or suggestion phases we could show all past themes for reference, or a "This might be similar to...." UI element.

As far as voting goes, it's somewhat disheartening to see that the themes are usually ones that ended up being disliked the least, rather than everyone being actually excited about it. To that end, instead of mass-ranking all themes, if instead we picked our top 3? This accomplishes a similar result to ranking without the headaches. You pick one theme to get +3, then +2, then +1, and you're done.

**Comment by Cerno-b** [comment]
I like the -1 0 +1 better. It's called Theme Slaughter, and it's all about getting rid of themes that suck. -1 for me represents exactly that. 

If anything, I could imagine the final voting round adopting a 0/1/2 or even a 1/2/3/4/5 scheme. Here we got rid of all the junk and what remains has to have some merit.

**Comment by Jezzamonn** [comment]
@Cerno-b FYI Theme Slaughter is different to the Theme Voting. Slaughter happens before the voting, where you say good or bad to theme suggestions, out of the pool of every theme that's been suggested, voting is just the thing that happens in the last few weeks.

**Comment by Cerno-b** [comment]
Ah, sorry, I thought this was about the whole process. Well, then I wouldn't mind either way. 

Of course we could try preferential voting, which I generally like a lot. 

There are different options:
- every user can rank every theme on a scale from 0 to 9
- every user has 10 points to give and can distribute them among themes (accumulation on a single theme is allowed)
- every user has to rank the themes from best to worst (implying a score from 1 to 20)

However, these can be problematic if people want to game the system, as they could pile up their points on their favorite theme, which is currently possible as well, but with weighted values it would become much easier. On the upside, you may get more fine-grained information, especially with variant 3, which forces people to actually consider how much they like themes compared to others.
