### ISSUE TITLE
Max post length too short

### ISSUE THREAD

**Issue by Aurel300** [ludumdare/ludumdare#836]
8192 characters is just ridiculous for any Post-Mortem style entry.

**Comment by zwrawr** [comment]
You will be able to create two different kinds of content, posts and articles. Posts are more geared towards time sensitive 'status update' type content where as articles are meant to be more 'timeless' longer form content. 

I think post-mortem write ups defiantly fall into the category of articles. The issue is that users cannot publish articles yet. (The rules and hosting guide are articles btw).

**Comment by povrazor** [comment]
I've bumped the blog post limit to 24k characters. That should give enough headroom for most things. Other content types (games, users) are still 8k.
