### ISSUE TITLE
Huge thumbnail when browsing games

### ISSUE THREAD

**Issue by Aurel300** [ludumdare/ludumdare#915]
This just happened, it surprised me a bit:

![screen shot 2017-05-14 at 19 46 21](https://cloud.githubusercontent.com/assets/1102162/26036852/08bed2fc-38de-11e7-883a-a8492ac3cb3d.png)

I scrolled down and pressed More a couple of times, then suddenly this one game had a giant thumbnail. Pressing More once again fixed that, then the last two games had big thumbnails. I guess the game thumbnails adapt their size to fill their line. I feel it would be more fair to ensure every thumbnail is the same size :)

**Comment by povrazor** [comment]
Yeah it's a bit clumsy the way things are working right now. I needed a solution that would dynamically let the game artwork fit any width, and on the rest of the site we use cleverness to always return a multiple of 3 so most people wouldn't notice this.

**Comment by local-minimum** [comment]
When I was scrolling through the `zero` list I sometimes got to situations with only 2 games at the bottom row, while there were actually more games in the list and then clicking `MORE` games got loaded correctly so the next set ended up with 3 at the bottom row. So this to me means that it doesn't always load 12.

I'm guessing that what happens is that (using `grade` list as an example) that the first request getting 17 next items:

https://api.ldjam.com/vx/node/feed/1/grade/item/game/compo+jam+craft+release?offset=151&limit=17

My guess for 17 is that you don't know if you want to skip an entry before you've gotten it, because the filter `compo+jam+craft+release` doesn't require release they are `OR` filters.

Then as an example the following happens

https://api.ldjam.com/vx/node/get/24732+17564+22426+27456+17180+16475+15620+15615+16533+16318+19962+18703

Only 12 are actually requested. And I guess this is the error, we really wanted either to be able to request 17 to start and have `release` be required or at least be part of the response. This would be best for performance. Alternative, the second query should either

1. get all 17 nodes at once and only show the first 12 valid (the remaining could perhaps be stored invisible for next `MORE` click, then it is no performance loss and and actually enhance UX since there's no wait for the first next items...)
2. get first 12 and then follow up with however many are discarded

I think I could work on this bug, but I need to know from @povrazor which solution he likes the most

**Comment by povrazor** [comment]
I'm actually undecided what I want to do here. Bottom line though it needs to support displaying everything (with gaps) as once you reach the end of a list you need this. 

Holding back data is kinda nice since it keeps the layout perfect. We do need to support more than just 3 games wide though (which we don't yet).

**Comment by local-minimum** [comment]
Some people really hate on that more button and we could perhaps code it to stay ahead of the user a bit and have invisible content-boxes?

**Comment by zwrawr** [comment]
I don't get the hate on a more button, but we could just go to infinite scroll and fix the problem.
There was people wanting to be able to just jump to page 50(lets say) but i don't really get why they want that.

**Comment by local-minimum** [comment]
I think one issue with `More` is how much space there's left on fancy screens

![notfillup](https://cloud.githubusercontent.com/assets/8041100/26390822/7b9b1784-4060-11e7-8904-27b2ec009e89.png)

But more importantly, imagine you've clicked yourself to about game 100 in some list and accidentally miss ctrl for opening that game in new tab. Now going back you have to restart to get where you were.

**Comment by zwrawr** [comment]
This won't happen any more and pagination has a separate issue(#1324), this can be closed.
