### ISSUE TITLE
Require minimum rating to get grade.

### ISSUE THREAD

**Issue by local-minimum** [ludumdare/ludumdare#985]
I'm not 100% sure I stand by this suggestion, but worth discussing:

What if we for the next jam required e.g. 15 votes on others' games to get a rating combined with the need to get votes on your own game?

Some people express anger at very popular games with next to zero voting on others' and I agree to the extent that we need to foster a community and making sure everyone gives some feedback could be a step.

**Comment by zwrawr** [comment]
A lot of discussion [here](https://ldjam.com/events/ludum-dare/38/ludum-dare-dot-com/short-on-ratings-friday-new-features)

**Comment by local-minimum** [comment]
Also [here](https://ldjam.com/events/ludum-dare/38/fuel/ratings-1)

**Comment by pfefferminzz** [comment]
What is the actual minimum to recieve a ranking in a category?
I've seen a game being ranked with 12 ratings.

**Comment by local-minimum** [comment]
I think Mike played around this time to include as many as possible to get as few angry mails about why they didn't get a ranking.

**Comment by povrazor** [comment]
My new grading tool can tell me when a rating within a lower threshold will break in to the top 50 of a category. There were times when a game with 10 ratings won a category, but the highest score a game got was 8th in graphics. There were a total of 8 games in the top 50 across 16 categories (jam/compo) that wouldn't have made it otherwise. When that happens I can (as it was requested) tweak the minimums. I think it was only 50-some games in the 10-20 range that weren't going to get a score, so to try and maximize the effort everyone put in I included everything 10+ (again, only because it was safe).

**Comment by local-minimum** [comment]
Oh @povrazor what I was suggesting was not about number of votes on a game for it to be getting a rating, but if it could be good to require a number of votes on other peoples games before you get a final score independent of how many votes your game received.

**Comment by povrazor** [comment]
This is a philosophical question. I do realize the current setup permits popular users to be lazy, but not everybody Ludum Dares for the same reasons. I would rather take the approach that users that are active and benefit the judging and the community get noticed for that. It is harder to provide incentives for doing this. Prioritization is what we do today, but maybe we'll find other ways to make it worthwhile.

**Comment by local-minimum** [comment]
I like the softer incentive approach for my second algorithm in #986 better, but I get it's hard to look at the images and say much about it (which is why I'd love for the data of game average per category, number of votes received per category, and total votes given to others/coolness or something similar)
